tun-addr: 10.255.123.0
ssh:
  host: 127.0.0.1
  port: 22
  user-name: root
  #  auth-type 可选 password | identity 为identity时, passphrase可选
  auth-type: password
  password: password
  passphrase: passphrase
route-arr:
  #  路由地址以及掩码
  - addr: 172.10.0.0
    mask: 255.255.0.0